---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Hello World App"
host: "localhost:3000"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  JWT:
    description: "Authorization: Bearer {token}"
    type: "apiKey"
    name: "Authorization"
    in: "header"
security:
  - JWT: []
paths:
  /account/login:
    post:
      summary: "登录"
      description: "登录..."
      security: []
      parameters:
      - in: "body"
        name: "body"
        description: "登录参数"
        required: true
        schema:
          $ref: "#/definitions/LoginBody"
      responses:
        "200":
          description: "登录成功"
          schema:
            $ref: "#/definitions/LoginResponse"
  /account/user:
    get:
      summary: "查询当前用户"
      description: "查询当前用户.."
      responses:
        "200":
          description: "查询成功"
          headers:
            authtoken:
              type: string
              description: 新token续期
          schema:
            $ref: "#/definitions/UserDemo"
        "401":
          $ref: "#/responses/Unauthorized"
        "404":
          $ref: "#/responses/NotFound"
definitions:
  User:
    type: "object"
    x-isModel: true
    x-plural: "Users"
    x-tableName: "user"
    description: "用户"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "ID"
        uniqueItems: true
      name:
        type: "string"
        format: "string(64)"
        minLength: 4
        maxLength: 64
        description: "姓名"
        x-message: "请输入"
        x-showTable: true
      nickname:
        type: "string"
        format: "string(64)"
        description: "昵称"
        x-message: "请输入"
        x-showTable: true
      gender:
        type: "integer"
        format: "int4"
        enum: [0,1,2]
        default: 0
        x-message: "请选择"
        x-showTable: true
        x-showFilter: true
        x-enumMap: {
          0: "未知",
          1: "男",
          2: "女",
        }
        x-description: "性别"
        description: >
          "性别"
            * 0 - 未知
            * 1 - 男
            * 2 - 女
      avatar:
        type: "string"
        format: "string(255)"
        description: "头像"
        x-message: "请输入"
      mobile:
        type: "string"
        format: "string(11)"
        description: "手机"
        x-message: "请输入"
        x-showTable: true
      email:
        type: "string"
        format: "email"
        description: "邮箱"
        x-message: "请输入"
        x-showTable: true
      birthday:
        type: "string"
        format: "date"
        description: "生日"
        x-message: "请选择"
        x-showTable: true
        x-showSorter: true
    example:
      id: "123"
      name: "foo"
      gender: 0
      birthday: "2012-12-12"
      email: "test@test.com"
  PwdAuth:
    type: "object"
    x-isModel: true
    x-plural: "PwdAuths"
    x-tableName: "pwdauth"
    description: "密码认证"
    required:
      - "id"
      - "user_id"
      - "username"
      - "password"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "ID"
        uniqueItems: true
      user_id:
        type: "string"
        format: "uuid"
        description: "账号ID"
        x-message: "请输入"
        x-showTable: true
      username:
        type: "string"
        format: "string(64)"
        minLength: 4
        maxLength: 64
        description: "账号"
        x-message: "请输入"
        x-showTable: true
        uniqueItems: true
      mobile:
        type: "string"
        format: "string(11)"
        description: "手机"
        x-message: "请输入"
        x-showTable: true
        uniqueItems: true
      email:
        type: "string"
        format: "email"
        description: "邮箱"
        x-message: "请输入"
        x-showTable: true
        uniqueItems: true
      password:
        type: "string"
        format: "string(64)"
        description: "密码"
        x-message: "请输入"
      expire_time:
        type: "string"
        format: "date-time"
        description: "过期时间"
        x-showTable: true
        x-showSorter: true
      verify_time:
        type: "string"
        format: "date-time"
        description: "认证时间"
        x-showTable: true
        x-showSorter: true
    example:
      id: "123"
      user_id: '456'
      username: "foo"
  ThirdAuth:
    type: "object"
    x-isModel: true
    x-plural: "ThirdAuths"
    x-tableName: "thirdauth"
    description: "三方认证"
    required:
      - "id"
      - "user_id"
      - "auth_type"
      - "auth_id"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "ID"
        uniqueItems: true
      user_id:
        type: "string"
        format: "uuid"
        description: "账号ID"
        x-message: "请输入"
        x-showTable: true
      auth_type:
        type: "string"
        format: "string(16)"
        description: "认证类型"
        x-message: "请输入"
        x-showTable: true
      auth_id:
        type: "string"
        format: "string(64)"
        description: "认证账号(appid)"
        x-message: "请输入"
        x-showTable: true
      auth_code:
        type: "string"
        format: "string(128)"
        description: "认证凭证(openid)"
        x-message: "请输入"
        x-showTable: true
      expire_time:
        type: "string"
        format: "date-time"
        description: "过期时间"
        x-showTable: true
        x-showSorter: true
      verify_time:
        type: "string"
        format: "date-time"
        description: "认证时间"
        x-showTable: true
        x-showSorter: true
    example:
      id: "123"
      user_id: '456'
      auth_type: "weixin"
      auth_id: 'wx123456'
  UserDemo:
    type: "object"
    description: "用户模型"
    required:
      - "id"
      - "name"
    properties:
      id:
        type: "integer"
        description: "ID"
      name:
        type: "string"
        description: "用户名"
      avatar:
        type: "string"
        description: "头像"
      email:
        type: "string"
        description: "邮箱"
    example:
      name: 'Admin'
      avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png'
      id: '00000001'
      email: 'test@test.com'
  LoginBody:
    type: "object"
    description: "登录参数模型"
    required:
      - "userName"
      - "password"
      - "type"
    properties:
      userName:
        type: "string"
        description: "用户名"
      password:
        type: "string"
        description: "密码"
      type:
        type: "string"
        description: "账户类型"
    example:
      userName: 'admin'
      password: '123456'
      type: 'username'
  LoginResponse:
    type: "object"
    description: "登录返回数据模型"
    required:
      - "status"
      - "type"
      - "currentAuthority"
      - "authtoken"
    properties:
      status:
        type: "string"
        description: "登录状态"
      type:
        type: "string"
        description: "账号类型"
      currentAuthority:
        type: "string"
        description: "当前角色"
      authtoken:
        type: "string"
        description: "秘钥"
  Error:
    type: "object"
    properties:
      message:
        type: "string"
      errors:
        type: "array"
        items:
          $ref: '#/definitions/ErrorItem'
    required:
      - "message"
  ErrorItem:
    type: "object"
    properties:
      errcode:
        type: "integer"
      errmsg:
        type: "string"
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
      
      
